# === Generated by AIBasic Compiler ===

# 10 send message "Hello from AIbasic!"
from aibasic.modules import TelegramModule
telegram = TelegramModule()
result = telegram.send_message(text='Hello from AIbasic!')
