from goto import with_goto

# === Generated by AIBasic Compiler ===

@with_goto
def main():
    label .line_10
    # 10 set counter to 0
    counter = 0

    label .line_20
    # 20 print counter
    print(counter)

    label .line_30
    # 30 increment counter by 1
    counter += 1

    label .line_40
    # 40 if counter is less than 3 jump to line 20
    _aibasic_jump_condition = (counter < 3)
    if locals().get('_aibasic_jump_condition', False):
        goto .line_20

    label .line_50
    # 50 print "Done!"
    print("Done!")

if __name__ == '__main__':
    main()
