# === Generated by AIBasic Compiler ===
# Manual test for CALL and RETURN

def _line_10():
    global _next_line, _call_stack
    # 10 print "Main program start"
    print("Main program start")
    if _next_line is None:
        _next_line = 20

def _line_20():
    global _next_line, _call_stack, x
    # 20 set x to 5
    x = 5
    if _next_line is None:
        _next_line = 30

def _line_30():
    global _next_line, _call_stack
    # 30 call 1000
    _call_stack.append(40)
    _next_line = 1000

def _line_40():
    global _next_line, _call_stack, x
    # 40 print x
    print(f"x after first call: {x}")
    if _next_line is None:
        _next_line = 50

def _line_50():
    global _next_line, _call_stack
    # 50 call 1000
    _call_stack.append(60)
    _next_line = 1000

def _line_60():
    global _next_line, _call_stack, x
    # 60 print x
    print(f"x after second call: {x}")
    if _next_line is None:
        _next_line = 70

def _line_70():
    global _next_line, _call_stack
    # 70 print "Main program end"
    print("Main program end")

def _line_1000():
    global _next_line, _call_stack, x
    # 1000 print "In subroutine"
    print("In subroutine")
    if _next_line is None:
        _next_line = 1010

def _line_1010():
    global _next_line, _call_stack, x
    # 1010 multiply x by 2
    x = x * 2
    if _next_line is None:
        _next_line = 1020

def _line_1020():
    global _next_line, _call_stack
    # 1020 return
    if _call_stack:
        _next_line = _call_stack.pop()
    else:
        _next_line = None

def main():
    global _next_line, _call_stack, x
    _current_line = 10
    _next_line = None
    _call_stack = []  # Stack for subroutine return addresses

    # Line dispatch table
    _line_functions = {
        10: _line_10,
        20: _line_20,
        30: _line_30,
        40: _line_40,
        50: _line_50,
        60: _line_60,
        70: _line_70,
        1000: _line_1000,
        1010: _line_1010,
        1020: _line_1020,
    }

    while _current_line is not None:
        _next_line = None
        line_func = _line_functions.get(_current_line)
        if line_func:
            line_func()
        else:
            break
        _current_line = _next_line

if __name__ == '__main__':
    main()
