#!/usr/bin/env python3
"""
Test to verify the import instructions are clear in the prompt.
Shows how the LLM should handle imports for module usage.
"""

import sys
from pathlib import Path

# Fix Windows console encoding
if sys.platform == 'win32':
    import io
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

print("=" * 80)
print("IMPORT INSTRUCTIONS TEST")
print("=" * 80)

print("""
PROBLEMA IDENTIFICATO:
---------------------
L'LLM stava mettendo "from aibasic.modules import TelegramModule" in needs_imports.
Il compilatore aggiungeva "import " davanti, creando:
  → import from aibasic.modules import TelegramModule  ❌

SOLUZIONE:
----------
1. SYSTEM_PROMPT modificato per chiarire needs_imports
2. Istruzioni specifiche per moduli: import va nel "code", non in "needs_imports"
3. Esempi JSON CORRETTI e SBAGLIATI

NUOVO SYSTEM_PROMPT (estratto):
-------------------------------
""")

print('''
- "needs_imports": array of strings — each string is ONLY what comes after "import" keyword.
  EXAMPLES:
  ✓ CORRECT: ["pandas as pd", "os", "json"]
  ✓ CORRECT: [] (empty if imports already in code)
  ✗ WRONG: ["import pandas as pd"]
  ✗ WRONG: ["from os import path"]

  NOTE: The compiler will add "import " prefix automatically.
  If you need "from X import Y", put it directly in the "code" field instead.
''')

print("\nNUOVE ISTRUZIONI PER MODULI:")
print("-" * 80)
print('''
5. IMPORTS: Put the import statement DIRECTLY in your code
   - Include: from aibasic.modules import TelegramModule
   - Put it in the "code" field, NOT in "needs_imports"
   - "needs_imports" should be [] (empty) for module usage

CORRECT JSON RESPONSE:
{
  "code": "from aibasic.modules import TelegramModule\\ntelegram = TelegramModule()\\nresult = telegram.send_message(text='Hello')",
  "context_updates": {"telegram": "Telegram module instance", "result": "message result", "last_output": "result"},
  "needs_imports": []
}

WRONG JSON RESPONSE (DO NOT DO THIS):
{
  "code": "telegram.send_message(text='Hello')",
  "needs_imports": ["from aibasic.modules import TelegramModule"]  // WRONG!
}
''')

print("\n" + "=" * 80)
print("COME IL COMPILATORE GESTISCE GLI IMPORT")
print("=" * 80)
print("""
Il compilatore fa questo alla fine (aibasicc.py:1290-1293):

    if collected_imports:
        for imp in sorted(collected_imports):
            f.write(f"import {imp}\\n")  # <-- Aggiunge "import " davanti

Quindi needs_imports deve contenere SOLO:
  ✓ "pandas as pd"  → diventa: import pandas as pd
  ✓ "os"            → diventa: import os
  ✓ "json"          → diventa: import json

NON:
  ✗ "from aibasic.modules import X"  → diventerebbe: import from aibasic.modules import X

Per "from X import Y", l'LLM deve metterlo direttamente nel campo "code".
""")

print("\n" + "=" * 80)
print("ESEMPIO COMPLETO PER TELEGRAM")
print("=" * 80)
print("""
INPUT AIbasic:
  10 (telegram) send message "Hello from AIbasic!"

LLM dovrebbe rispondere con:
{
  "code": "from aibasic.modules import TelegramModule\\nif 'telegram' not in locals():\\n    telegram = TelegramModule()\\nresult = telegram.send_message(text='Hello from AIbasic!')",
  "context_updates": {
    "telegram": "TelegramModule instance for sending messages",
    "result": "Result of send_message call",
    "last_output": "result"
  },
  "needs_imports": []
}

Output finale (dopo compilazione):
  # === Generated by AIBasic Compiler ===

  # 10 send message "Hello from AIbasic!"
  from aibasic.modules import TelegramModule
  if 'telegram' not in locals():
      telegram = TelegramModule()
  result = telegram.send_message(text='Hello from AIbasic!')

✅ Nessun doppio import!
✅ Codice pulito e funzionante!
""")

print("\n" + "=" * 80)
print("VERIFICA")
print("=" * 80)
print("""
Per verificare che funzioni:

1. Compila un file test:
   echo '10 (telegram) send message "Test"' > test.aib
   python src/aibasic/aibasicc.py -c aibasic.conf -i test.aib -o output.py

2. Controlla output.py:
   cat output.py | head -10

3. Verifica che ci sia:
   ✓ "from aibasic.modules import TelegramModule" (una sola volta)
   ✓ "telegram = TelegramModule()"
   ✓ "telegram.send_message(...)"

4. Verifica che NON ci sia:
   ✗ "import from aibasic.modules"
   ✗ "from from aibasic.modules"
   ✗ Doppi import

Se l'output è corretto, il problema è risolto! ✅
""")

print("\n" + "=" * 80)
print("CONCLUSIONE")
print("=" * 80)
print("""
✅ SYSTEM_PROMPT chiarito con esempi espliciti
✅ Istruzioni moduli specificano: import nel "code", needs_imports vuoto
✅ Esempi JSON CORRETTI e SBAGLIATI forniti
✅ Spiegato COME il compilatore processa needs_imports

L'LLM ora ha istruzioni chiare e non ambigue su come gestire gli import!
""")
