# === Generated by AIBasic Compiler ===
# Manual test for error handling

def _line_10():
    global _next_line, _error_handler, x
    # 10 print "Starting..."
    print("Starting...")
    if _next_line is None:
        _next_line = 20

def _line_20():
    global _next_line, _error_handler, x
    # 20 on error goto 50
    _error_handler = 50
    if _next_line is None:
        _next_line = 30

def _line_30():
    global _next_line, _error_handler, x
    # 30 set x to 10
    x = 10
    if _next_line is None:
        _next_line = 40

def _line_40():
    global _next_line, _error_handler, x
    # 40 divide x by 0 (will cause error)
    result = x / 0
    print(f"Result: {result}")
    if _next_line is None:
        _next_line = 60

def _line_50():
    global _next_line, _error_handler
    # 50 print error message
    print(f"ERROR CAUGHT!")
    print(f"Error was: {globals().get('_last_error', 'Unknown')}")
    print(f"Error at line: {globals().get('_last_error_line', 'Unknown')}")
    if _next_line is None:
        _next_line = 60

def _line_60():
    global _next_line, _error_handler
    # 60 print "Done"
    print("Done")

def main():
    global _next_line, _error_handler, x
    _current_line = 10
    _next_line = None
    _error_handler = None  # Error handler line number

    # Line dispatch table
    _line_functions = {
        10: _line_10,
        20: _line_20,
        30: _line_30,
        40: _line_40,
        50: _line_50,
        60: _line_60,
    }

    while _current_line is not None:
        _next_line = None
        line_func = _line_functions.get(_current_line)
        if line_func:
            try:
                line_func()
            except Exception as e:
                if _error_handler is not None:
                    # Store error information in globals
                    globals()['_last_error'] = e
                    globals()['_last_error_line'] = _current_line
                    _next_line = _error_handler
                else:
                    raise  # Re-raise if no error handler is set
        else:
            break
        _current_line = _next_line

if __name__ == '__main__':
    main()
