# === Generated by AIBasic Compiler ===

def main():
    _current_line = 10
    _next_line = None

    while _current_line is not None:
        _next_line = None
        if _current_line == 10:
        # 10 set counter to 0
            counter = 0
            if _next_line is None:
                _next_line = 20
        elif _current_line == 20:
        # 20 print counter
            print(counter)
            if _next_line is None:
                _next_line = 30
        elif _current_line == 30:
        # 30 increment counter by 1
            counter += 1
            if _next_line is None:
                _next_line = 40
        elif _current_line == 40:
        # 40 if counter is less than 3 jump to line 20
            _aibasic_jump_condition = (counter < 3)
            if _aibasic_jump_condition:
                _next_line = 20
            if _next_line is None:
                _next_line = 50
        elif _current_line == 50:
        # 50 print "Done!"
            print("Done!")
        else:
            break

        _current_line = _next_line

if __name__ == '__main__':
    main()
