# === Generated by AIBasic Compiler ===

def _line_10():
    global _next_line, counter
    # 10 set counter to 0
    counter = 0
    if _next_line is None:
        _next_line = 20

def _line_20():
    global _next_line, counter
    # 20 print counter
    print(counter)
    if _next_line is None:
        _next_line = 30

def _line_30():
    global _next_line, counter
    # 30 increment counter by 1
    counter += 1
    if _next_line is None:
        _next_line = 40

def _line_40():
    global _next_line, counter
    # 40 if counter is less than 3 jump to line 20
    _aibasic_jump_condition = (counter < 3)
    if _aibasic_jump_condition:
        _next_line = 20
    if _next_line is None:
        _next_line = 50

def _line_50():
    global _next_line
    # 50 print "Done!"
    print("Done!")

def main():
    global _next_line, counter
    _current_line = 10
    _next_line = None

    # Line dispatch table
    _line_functions = {
        10: _line_10,
        20: _line_20,
        30: _line_30,
        40: _line_40,
        50: _line_50,
    }

    while _current_line is not None:
        _next_line = None
        line_func = _line_functions.get(_current_line)
        if line_func:
            line_func()
        else:
            break
        _current_line = _next_line

if __name__ == '__main__':
    main()
